#!/usr/bin/env zsh

# pull (fetch + merge) from main and FORCE overwrite
# WARNING - all local changes will be lost

# do local commit first
sh git/commit

# fetch changes and overwrite if there is a conflict
git fetch origin main
git merge -s recursive -X theirs origin/master